/* FRONTIER SYSTEMS / SHARED RUNTIME v1.0
   One interface system across all Frontier divisions.
*/
(()=>{"use strict";
const LANG_KEY="frontier-language";
const supported=["en","ru","zh","ja","ko","de","fr","es","pt","ar","tr","hi"];
const detect=()=>{try{const s=localStorage.getItem(LANG_KEY);if(s&&supported.includes(s))return s}catch(e){}const n=(navigator.languages||[navigator.language||"en"]).map(x=>x.toLowerCase().split("-")[0]);return n.find(x=>supported.includes(x))||"en"};
const setLanguage=(lang)=>{if(!supported.includes(lang))lang="en";try{localStorage.setItem(LANG_KEY,lang)}catch(e){}document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.dispatchEvent(new CustomEvent("frontier:language",{detail:{lang}}));};
const setupLanguage=()=>{const current=detect();setLanguage(current);document.querySelectorAll("[data-language-select]").forEach(select=>{select.value=current;select.addEventListener("change",()=>setLanguage(select.value))});};
const setupReducedMotion=()=>{const media=matchMedia("(prefers-reduced-motion: reduce)");document.documentElement.classList.toggle("reduced-motion",media.matches);media.addEventListener?.("change",e=>document.documentElement.classList.toggle("reduced-motion",e.matches));};
const setupViewport=()=>{const root=document.documentElement;const sync=()=>{root.style.setProperty("--vw",innerWidth+"px");root.style.setProperty("--vh",innerHeight+"px");root.style.setProperty("--safe-top","env(safe-area-inset-top, 0px)");root.style.setProperty("--safe-bottom","env(safe-area-inset-bottom, 0px)")};sync();addEventListener("resize",sync,{passive:true});};
const setupAnchorMotion=()=>{document.addEventListener("click",e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const id=a.getAttribute("href");if(!id||id==="#")return;const target=document.querySelector(id);if(target){e.preventDefault();target.scrollIntoView({behavior:document.documentElement.classList.contains("reduced-motion")?"auto":"smooth",block:"start"});history.replaceState(null,"",id)}})};
const setupCommand=()=>{const trigger=document.querySelector("[data-command-trigger]");if(!trigger)return;let panel=document.querySelector("[data-command-panel]");if(!panel){panel=document.createElement("div");panel.dataset.commandPanel="";panel.hidden=true;panel.setAttribute("role","dialog");panel.setAttribute("aria-modal","true");panel.setAttribute("aria-label","Navigation");const seen=new Set(),links=[...document.querySelectorAll("nav .nav a[href]")].filter(a=>{const k=a.getAttribute("href")+"|"+a.textContent.trim();if(seen.has(k))return false;seen.add(k);return true});panel.innerHTML='<div class="frontier-command-card"><div class="frontier-command-head"><strong>ROOT FRONTIER SYSTEMS</strong><button type="button" data-command-close aria-label="Close navigation">×</button></div><div class="frontier-command-links"></div></div>';const box=panel.querySelector(".frontier-command-links");links.forEach(a=>{const x=document.createElement("a");x.href=a.getAttribute("href");x.textContent=a.textContent.trim();box.appendChild(x)});const style=document.createElement("style");style.textContent='[data-command-panel]{position:fixed;inset:0;z-index:120;background:rgba(3,4,6,.9);backdrop-filter:blur(18px);padding:84px 16px 24px;display:flex;align-items:flex-start;justify-content:center}[data-command-panel][hidden]{display:none!important}.frontier-command-card{width:min(680px,100%);max-height:calc(100svh - 110px);overflow:auto;background:#080a0d;border:1px solid #303742;padding:20px}.frontier-command-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding-bottom:16px;border-bottom:1px solid #252c34;font-size:.68rem;letter-spacing:.12em}.frontier-command-head button{border:1px solid #46515c;background:none;color:inherit;width:38px;height:38px;cursor:pointer}.frontier-command-links{display:grid;padding-top:8px}.frontier-command-links a{display:block;padding:15px 8px;border-bottom:1px solid #202630;font-size:.8rem;letter-spacing:.08em;text-transform:uppercase}.frontier-command-links a:hover{background:rgba(255,255,255,.04)}';document.head.appendChild(style);document.body.appendChild(panel)}const open=()=>{panel.hidden=false;document.body.classList.add("command-open");trigger.setAttribute("aria-expanded","true");panel.querySelector("a,button,input")?.focus()};const close=()=>{panel.hidden=true;document.body.classList.remove("command-open");trigger.setAttribute("aria-expanded","false")};trigger.setAttribute("aria-haspopup","dialog");trigger.setAttribute("aria-expanded","false");trigger.addEventListener("click",()=>panel.hidden?open():close());panel.querySelector("[data-command-close]")?.addEventListener("click",close);panel.querySelectorAll("a").forEach(a=>a.addEventListener("click",close));panel.addEventListener("click",e=>{if(e.target===panel)close()});addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();panel.hidden?open():close()}if(e.key==="Escape"&&!panel.hidden)close()})};
const setupPointer=()=>{let raf=0,x=innerWidth*.5,y=innerHeight*.4;addEventListener("pointermove",e=>{x=e.clientX;y=e.clientY;if(raf)return;raf=requestAnimationFrame(()=>{document.documentElement.style.setProperty("--pointer-x",x+"px");document.documentElement.style.setProperty("--pointer-y",y+"px");raf=0})},{passive:true})};
const boot=()=>{setupViewport();setupReducedMotion();setupLanguage();setupAnchorMotion();setupCommand();setupPointer();document.documentElement.dataset.frontierRuntime="1.0"};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
window.FrontierRuntime={version:"1.0",supportedLanguages:supported,detectLanguage:detect,setLanguage};
})();